### PR TITLE
Prop-types + dependency updates

### PR DESCRIPTION
**Pull request by diegocouto**
This is a merge between the [pull request #314](https://github.com/shoutem/ui/pull/314) and an updated dependencies list in package.json.

### CODE REVIEW

**Comment by StanSarr** [comment]
@diegocouto I'm gonna use your Shoutem UI. Is it ok for you bud? 
Do you another errors, bugs etc...?

**Comment by diegocouto** [comment]
Sure, @StanSarr! If you find any other issues with Shoutem UI dependencies that should be updated to work well with React v16, just let me know that I'll update it. 😁 

**Edit**
Regarding the errors, I'm currently using it on a project and it works just fine.

**Comment by StanSarr** [comment]
Cool thank you. I'll let you know 👍

**Comment by dailycommit** [comment]
hey @diegocouto the original shoutem/ui does not work with react v16.0.0
How do I install your version ?
``npm install @shoutem/ui#pull/314/head`` does it work?

**Comment by diegocouto** [comment]
Hi, @dailycommit! Yep, unfortunately, it doesn't. 😞 

As I've merged the proposed changes on my fork and pushed them to master, you can use it through: `npm install diegocouto/ui`

**Comment by dailycommit** [comment]
Thanks for your help @diegocouto, It seems I'll have to change many codes for ``diegocouto/ui`` 🤓

**Pull request merged**
